name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run OAPI-Generate
      run: export PATH=${PATH}:/usr/local/go/bin && make gen
      
    - name: Run Lint
      run: export PATH=${PATH}:/usr/local/go/bin && make lint

    - name: Run Format
      run: export PATH=${PATH}:/usr/local/go/bin && make fmt

    - name: Make Build Go
      run: export PATH=${PATH}:/usr/local/go/bin && make build-go

    - name: Make Build Docker Images
      run: export PATH=${PATH}:/usr/local/go/bin && make build-docker
