name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.21.5' # The Go version to download (if necessary) and use.

    - name: Run OAPI-Generate
      run: make gen
      
    - name: Run Lint
      run: make lint

    - name: Run Format
      run: make fmt

    - name: Make Build Go
      run: make build-go

    - name: Make Build Docker Images
      run: make build-image
